incremental

diff --git a/bin/run b/bin/run
--- a/bin/run
+++ b/bin/run
@@ -1,8 +1,13 @@
 #!/usr/bin/env bash
 
 error() {
+  local code_name=$1; shift
   local chip_barcode=$1; shift
-  echo "Error: "$@" | tee ${FAILED_DIR}/${chip_barcode}.txt 1>&2
+  local msg=$1; shift
+
+  make_dir ${FAILED_DIR}/${code_name}
+
+  echo "Error: $msg" | tee ${FAILED_DIR}/${code_name}/${chip_barcode}.txt 1>&2
   exit 1
 }
 
@@ -26,8 +31,7 @@ check_have_group() {
 
   local id_output=$( id )
   if ! echo ${id_output} | grep -q "\<${group}\>"; then
-    error $chip_barcode \
-      "Exiting. Node dropped '${group}' group ownership in session, data inaccessible. id-output: ${id_output}"
+    error $chip_barcode "Exiting. Node dropped '${group}' group ownership in session, data inaccessible. id-output: ${id_output}"
   fi
 }
 
