simplifying things - now copying data to $HOME prior to batch submital

diff --git a/bin/run b/bin/run
--- a/bin/run
+++ b/bin/run
@@ -1,96 +1,47 @@
 #!/usr/bin/env bash
 
-error() {
-  local code_name=$1; shift
-  local chip_barcode=$1; shift
-  local msg=$1; shift
-
-  create_dir ${FAILED_DIR}/${code_name}
-
-  echo "Error: $msg" | tee ${FAILED_DIR}/${code_name}/${chip_barcode}.txt 1>&2
-  exit 1
-}
-
-create_dir() {
-  local dir="$1"
-  [[ -d ${dir} ]] || mkdir -p ${dir}
-}
-
-usage() {
-  echo "Usage: $( basename $0 ) <code> [chip_barcode] [chip_barcode..]" 1>&2
-  exit 1
-}
-
-filter_excluded() {
-  grep -v '/level2' | grep -v '7911755025' | grep -v '\.zip$'
-}
+BASE="$(readlink -f $(readlink -f $(dirname "${BASH_SOURCE}")/..))"
 
 check_have_group() {
   local group=$1
-  local code_name=$2
-  local chip_barcode=$3
-
   local id_output=$( id )
   if ! echo ${id_output} | grep -q "\<${group}\>"; then
-    error ${code_name} ${chip_barcode} \
-      "Exiting. Node dropped '${group}' group ownership in session, data inaccessible. id-output: ${id_output}"
+    error "Exiting. Node dropped '${group}' group ownership in session, data inaccessible. id-output: ${id_output}"
   fi
 }
 
-copy_data() {
-  local chip_barcode=$1
+clear_previous_job() {
+  for f in \
+    $COMPLETE_DIR/$CODE_NAME/$CHIP_BARCODE.txt \
+    $FAILED_DIR/$CODE_NAME/$CHIP_BARCODE.txt \
+    $RAW_QC_DIR; do
+    echo $f
 
-  create_dir ${DEST_DATA_DIR}/${chip_barcode}
-
-  for f in $( find ${SOURCE_DATA_DIR} -type f -name "${chip_barcode}*" | filter_excluded ); do
-    [[ -f ${DEST_DATA_DIR}/${chip_barcode}/$( basename ${f} ) ]] || cp -v ${f} ${DEST_DATA_DIR}/${chip_barcode}
+    [[ -e $f ]] && echo rm -rf $f
   done
+}
+
+error_and_exit() {
+  local msg=$1
+  echo "Error: $msg" | tee $FAILED_DIR/$CODE_NAME/$CHIP_BARCODE.txt 1>&2
+  exit 1
 }
 
 mark_job_complete() {
-  local code_name=$1
-  local chip_barcode=$2
-
-  [[ -d ${COMPLETE_DIR}/${code_name} ]] || mkdir -p ${COMPLETE_DIR}/${code_name}
-
-  date +%FT%T > ${COMPLETE_DIR}/${code_name}/${chip_barcode}.txt
+  date +%FT%T > $COMPLETE_DIR/$CODE_NAME/$CHIP_BARCODE.txt
 }
 
-clear_job_complete() {
-  local code_name=$1
-  local chip_barcode=$2
-
-  if [[ -f ${COMPLETE_DIR}/${code_name}/${chip_barcode}.txt ]]; then
-    rm ${COMPLETE_DIR}/${code_name}/${chip_barcode}.txt
-  fi
+setup_dirs() {
+  [[ -d $COMPLETE_DIR/$CODE_NAME ]] || mkdir -p $COMPLETE_DIR/$CODE_NAME
+  [[ -d $FAILED_DIR/$CODE_NAME ]] || mkdir -p $FAILED_DIR/$CODE_NAME
 }
 
-main() {
-  local code=${1}; shift
-  local chip_barcodes="${@:-3998755068}" # default for testing
-
-  local code_name=$( basename $code .R )
-
-  module load apps/R/${R_VERSION:-3.2.3}
-
-  for chip_barcode in ${chip_barcodes}; do
-
-    check_have_group hii ${code_name} ${chip_barcode}
-
-    clear_job_complete ${code_name} ${chip_barcode}
-
-    local raw_qc_dir=${WORK_DIR}/${code_name}/${chip_barcode}/raw/qc
-    mkdir -p ${raw_qc_dir}
-
-    copy_data ${chip_barcode}
-
-    R --slave --quiet --no-restore --no-save --args ${DEST_DATA_DIR}/${chip_barcode} ${raw_qc_dir} < ${code}
-
-    [[ $? == 0 ]] && mark_job_complete ${code_name} ${chip_barcode}
-  done
+usage() {
+  echo "Usage: $( basename $0 ) <code> [chip_barcode]" 1>&2
+  exit 1
 }
 
-BASE="$(readlink -f $(readlink -f $(dirname "${BASH_SOURCE}")/..))"
+R_VERSION=${R_VERSION:-3.2.3}
 
 SOURCE_DATA_DIR="${SOURCE_DATA_DIR:-/hiidata/teddy/data/jinfiniti/gene_expression}"
 
@@ -104,8 +55,34 @@ COMPLETE_DIR="${COMPLETE_DIR:-$BASE/tmp/complete}"
 
 FAILED_DIR="${FAILED_DIR:-$BASE/tmp/failed}"
 
-cd $BASE
+DEFAULT_CHIP_BARCODE="${DEFAULT_CHIP_BARCODE:-3998755068}" # for easy testing
+
+#---------------------------------------------------------------
+# main
+#---------------------------------------------------------------
 
 [[ $# < 1 ]] && usage
 
-main "$@"
+CODE=$1
+
+CHIP_BARCODE="${2:-$DEFAULT_CHIP_BARCODE}"
+
+CODE_NAME=$( basename $CODE .R )
+
+RAW_QC_DIR=$WORK_DIR/$CODE_NAME/$CHIP_BARCODE/raw/qc
+
+clear_previous_job
+
+setup_dirs
+
+module load apps/R/${R_VERSION}
+
+R --slave --quiet --no-restore --no-save --args $DEST_DATA_DIR/$CHIP_BARCODE $RAW_QC_DIR < $CODE
+
+rc=$?
+
+if [[ $rc == 0 ]]; then
+  mark_job_complete
+else
+  error_and_exit "R failed with return code: $rc"
+fi
