added check to make sure the R script provided exists

diff --git a/bin/slurm-submit b/bin/slurm-submit
--- a/bin/slurm-submit
+++ b/bin/slurm-submit
@@ -32,6 +32,10 @@ array_count=$( wc -l ${array_map} | awk '{print $1}' )
 
 sleep_command="$BASE/bin/util/random-sleep $SUBMIT_RANDOM_SECONDS"
 
+if ! [[ -f "${code}" ]]; then
+  echo "Error: R Script '${code}' does not exist. Exiting." 1>&2
+fi
+
 set -x
 
 sbatch \
