checkpoint - refactored combine-normalized-methods and seems to be working

diff --git a/bin/util/combine-normalized-methods b/bin/util/combine-normalized-methods
--- a/bin/util/combine-normalized-methods
+++ b/bin/util/combine-normalized-methods
@@ -7,41 +7,38 @@ source $BASE/lib/util.sh
 
 donors="1 2"
 
-prefixes="
-${WORK_DIR}/method-${method}-step-1-donor/combined/
-${WORK_DIR}/method-${method}-step-1-all/combined/
-"
-
 remove_bad_value_lines() {
   egrep -v '\<NaN\>|\<Inf\>|\<-Inf\>|\<NA\>'
 }
 
+subset=$1
 
 for method in $METHODS; do
 
-  for prefix in ${prefixes}; do
+  prefix="${WORK_DIR}/method-${method}-step-1-${subset}/combined/"
 
-    for donor in $donors; do
+  for donor in $donors; do
 
-      for suffix in "" "_filter"; do
+    for suffix in "" "_filter"; do
 
-        dest_dir=${WORK_DIR}/combine-normalized-methods/donor-${donor}${suffix}
+      dest_dir=${WORK_DIR}/combine-normalized-methods/${subset}/donor-${donor}${suffix}
 
-        mkdir -p ${dest_dir}
+      mkdir -p ${dest_dir}
 
-        if [[ -f ${prefix}/donor_${donor}_expression_normalized.txt ]]; then
-        remove_bad_value_lines < ${prefix}/donor_${donor}_expression_normalized${suffix}.txt \
+      if [[ -f ${prefix}/donor_${donor}_expression_normalized.txt ]]; then
+        cat ${prefix}/donor_${donor}_expression_normalized${suffix}.txt \
+          | remove_bad_value_lines \
             > ${dest_dir}/donor_${donor}-method-${method}_expression_normalized${suffix}.txt
 
-        elif [[ -f ${prefix}/donor_${donor}_expression_normalized_lumi.txt ]]; then
-          remove_bad_value_lines < ${prefix}/donor_${donor}_expression_normalized${suffix}_lumi.txt \
+      elif [[ -f ${prefix}/donor_${donor}_expression_normalized_lumi.txt ]]; then
+        cat ${prefix}/donor_${donor}_expression_normalized${suffix}_lumi.txt \
+          | remove_bad_value_lines \
             > ${dest_dir}/donor_${donor}-method-${method}_expression_normalized${suffix}_lumi.txt
-        else
-          echo "Error: Neither file exists: ${prefix}donor_${donor}_expression_normalized${suffix}.txt or " \
-              "${prefix}/donor_${donor}_expression_normalized${suffix}_lumi.txt" 1>&2
-          exit 1
-        fi
-      done
+      else
+        echo "Error: Neither file exists: ${prefix}donor_${donor}_expression_normalized${suffix}.txt or " \
+            "${prefix}/donor_${donor}_expression_normalized${suffix}_lumi.txt" 1>&2
+        exit 1
+      fi
     done
   done
 done
